### ISSUE TITLE
crypto.randomBytes throws TypeError in Node v20

### ISSUE THREAD

**Issue by ziflex** [auth0/passport-auth0#179] opened 2023-10-31 21:39 UTC
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/passport-auth0#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/passport-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After updating to Node v20, our application encounters a breaking change related to the crypto global variable. In this new version, crypto seems to point to a class and is immutable. As a result, [this line of code](https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L8) throws an exception:

```
Uncaught TypeError: crypto.randomBytes is not a function
```

### Reproduction

```bash
nvm use 20
node
```

```node
var crypto = require('crypto');
crypto.randomBytes(16).toString('hex')
```

<img width="414" alt="Screenshot 2023-10-31 at 5 47 03 PM" src="https://github.com/auth0/passport-auth0/assets/1607148/a8499e64-0b02-4956-ab32-20663ab6541f">

### passport-auth0 version

1.4.4

### Passport version

0.5.3

### Node.js version

20

**Comment by ziflex** [comment] 2023-10-31 21:46
The quick fix for this issue would be simply changing the variable's name from `crypto` to something else.
<img width="299" alt="Screenshot 2023-10-31 at 5 45 49 PM" src="https://github.com/auth0/passport-auth0/assets/1607148/8ef6a294-ccef-47f6-a493-29019b295ba4">

**Comment by adamjmcgrath** [comment] 2023-11-02 13:24
Hi @ziflex - thanks for raising this

What you're describing is a known issue in the Node 20 REPL (they have a test for it https://github.com/nodejs/node/blob/main/test/known_issues/test-cli-print-var-crypto.js)

But this shouldn't affect your application since you don't launch it from a REPL. If I create a file `foo.js` with your code example and run it using `node foo.js` - I won't get the error because global WebCrypto wont be enabled in this context.

**Comment by frederikprijck** [comment] 2023-11-14 12:08
Hey @ziflex ,

Can you verify the version of passport-auth0 you are using? We can reproduce this on 1.3.3, but not on 1.4.4.

Thanks

**Comment by frederikprijck** [comment] 2023-11-20 08:59
Closing, as I think this should be solved in the latest version. Can reopen if not.

**Closed by frederikprijck** 2023-11-20 08:59 UTC
Labels: bug
