### ISSUE TITLE
Un-caught error while login

### ISSUE THREAD

**Issue by techpool** [auth0/passport-auth0#31] opened 2016-09-28 02:15 UTC
Whenever a user is trying to login for some unknown reason this uncaught error comes in play.

```
TokenError: Invalid authorization code
   at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:320:12)
   at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /app/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /app/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/app/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:85:20)
   at IncomingMessage.emit (events.js:179:7)
   at endReadableNT (_stream_readable.js:913:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any help would be appreciated.

**Comment by omerlh** [comment] 2016-12-21 06:09
I had similar issue when testing callback endpoint with invalid access code. The expected behavior is 401, or redirect to login, not error.

**Comment by machuga** [comment] 2018-10-23 10:38
Closing due to age of request.

**Closed by machuga** 2018-10-23 10:38 UTC

**Comment by 90K2** [comment] 2019-03-17 04:50
success login callback give me such error so often

```
TokenError: Invalid authorization code
    at Strategy.OAuth2Strategy.parseErrorResponse (D:\Works\bitzlato\bitzlato-frontend\node_modules\passport-oauth2\lib\strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\Works\bitzlato\bitzlato-frontend\node_modules\passport-oauth2\lib\strategy.js:376:16)
    at D:\Works\bitzlato\bitzlato-frontend\node_modules\passport-oauth2\lib\strategy.js:166:45
    at D:\Works\bitzlato\bitzlato-frontend\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\Works\bitzlato\bitzlato-frontend\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\Works\bitzlato\bitzlato-frontend\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
