### ISSUE TITLE
userProfile error handler suppresses error message

### ISSUE THREAD

**Issue by ianwremmel** [auth0/passport-auth0#44] opened 2017-05-29 22:12 UTC
The `Error` constructor only takes a single parameter, so [this](https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L128) line suppresses errors produced by `oauth2.get`

```js
  this._oauth2.get(this.options.userInfoURL, accessToken, function (err, body, res) {
    if (err) { return done(new Error('failed to fetch user profile', err)); }
```

Is there any reason not to just do this?
```js
  this._oauth2.get(this.options.userInfoURL, accessToken, function (err, body, res) {
    if (err) { return done(err); }
```

**Comment by joshcanhelp** [comment] 2019-07-01 17:54
Duplicate of #41.

**Closed by joshcanhelp** 2019-07-01 17:54 UTC
