### ISSUE TITLE
could I use cookie-session instead of express-session?

### ISSUE THREAD

**Issue by jastsai** [auth0/passport-auth0#87] opened 2019-07-30 03:52 UTC
Sorry I am new to this,

I am wondering if I can use cookie-session instead of express-session since JWT is supposed to not storing information in server.

I am asking because I have read a few tutorial of passport and Auth0, and it also mentioned about expression-session only. 

I am facing issue with multiple instances + load balancer envrionment where after a user is login at Auth0 login page, and in /callback.

  router.get('/login', authenticate('auth0', { scope: 'openid email profile' }), (req, res) => res.redirect('/'));

  router.get('/callback', (req, res, next) => {
    authenticate('auth0', (authErr, user) => {

      if (authErr) {
        console.error(`Error authenticating user: ${authErr}`);
        return next(authErr);
      }
      if (!user) {
        return res.redirect('/login');
      }

 the user is set to false and eventually I see:

[xyzURL] redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Since Auth0 is using JWT, could I use cookie-session? if so, what could I do wrong?

PS.
Here is my session config:

    const sessionConfig = {
      name: 'sessionId',
      domain: 'example.com',
      secret: uid.sync(18),
      secure: true,
      httpOnly: true,
      maxAge: 1800 * 1000
    };

Thank you!

Jay

**Comment by joshcanhelp** [comment] 2019-08-01 20:09
Part of this is a duplicate of #86.

> ... since JWT is supposed to not storing information in server.

I'm not sure what you're saying here. Can you clarify?

As for using cookies ... I just tried `cookie-session` in place of `express-session` and it seemed to work as expected. It looks like that just switches the cookie to store the entire profile rather than just a session ID. 

I'm going to close this for now as it looks like you have what you need. Feel free to reply back if you need anything else!

**Closed by joshcanhelp** 2019-08-01 20:09 UTC

**Comment by jastsai** [comment] 2019-08-09 23:10
I got confused with JWT and Oauth2.  Sorry.
Oauth2 still needs a shared session store, and we chose to use cookie-session to store information at client's browser.

Looks like  making secret: [a fixed value] fixed my issue.

Thank you.

**Comment by jastsai** [comment] 2019-08-09 23:11
Thank you Josh for the reply and help.
